local dark = {
  base                  = "#262626",
  white                 = "#ffffff",
  main                  = "#FF0055",
  main_med              = "#ff3270",
  main_hard             = "#ff4081",
  secondary             = "#563466",
  secondary_light_      = "#283593",
  secondary_light_med   = "#d57bff",
  secondary_med         = "#c592ff",
  secondary_hard        = "#6766b3",
  accent                = "#76c1ff",
  secondary_accent      = "#00ffc8",
  secondary_accent_med  = "#00ff9c",
  secondary_accent_hard = "#00ffe9",
  secondary_accent_dark = "#00ff84",
  background_main       = "#120b10",
  background_secondary  = "#182333",
  background_accent     = "#101116",
  yellow                = "#fffc58",
  red                   = "#ff1745",
  whitespace            = "#2B3E5A",
  dark                  = "#140007",
  black                 = "#000000",
  none                  = "NONE",
  bold                  = "bold",
  underline             = "underline",
}

return dark
